CREATE TABLE recipes (
	id INTEGER(64) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(64),
	description TEXT
);
CREATE TABLE ingredients (
	id INTEGER(64) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	recipe INTEGER(64),
	name VARCHAR(64),
	amount TEXT
);